# Header
menu:
  主页: /
  所有文章: /archives
  学习笔记: /categories/学习笔记/
  关于: /about
  

# SubNav
subnav:
  github: https://github.com/huangww26
  weibo: http://weibo.com/2757197297
  zhihu: http://www.zhihu.com/people/huang-wei-wei-73-91
  mail: mailto:hweiwei3510@gmail.com  
  
  #zhihu: "#"
  #rss: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: img/penguin2.ico

#你的头像url
avatar: /img/author.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "hwwbd"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  码农圈: https://coderq.com
  开源中国: http://www.oschina.net/
  Minyi: http://qiumy.github.io/
  

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: false
